
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/07Magda_batchnorm.ipynb

from exp.nb_06cMagda import *