
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01Magda_matmul.ipynb

import gzip
from pathlib import Path
import torch
import pickle
import matplotlib as mpl
import matplotlib.pyplot as plt

def test_equal(a, b):
    assert torch.equal(a,b), f'{a} and {b} are not equal'

def test_near(a, b, rtol=1e-5, atol=1e-08):
    assert torch.allclose(a, b, rtol, atol), f'{a} and {b} are not near'