
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/04Magda_callbacks.ipynb

from torch.utils.data import TensorDataset, DataLoader

class DataBunch():
    def __init__(self, train_in, train_trg, valid_in, valid_trg, train_bs, valid_bs=None):
        self.train_data = TensorDataset(train_in, train_trg)
        self.valid_data = TensorDataset(valid_in, valid_trg)
        self.train_bs = train_bs
        self.valid_bs = len(valid_in) if valid_bs is None else valid_bs

    @property
    def train_dl(self):
        return DataLoader(self.train_data, self.train_bs, shuffle=True)

    @property
    def valid_dl(self):
        return DataLoader(self.valid_data, self.valid_bs, shuffle=False)

def get_accuracy(self, logits, targets):
    preds = logits.argmax(1)
    return (preds==targets).float().mean()